-- CreateTable
CREATE TABLE `M9Mex` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `folio` VARCHAR(191) NOT NULL,
    `fecha` DATETIME(3) NOT NULL,
    `tipoOrden` ENUM('INSTALACION', 'RETIRO', 'CAMBIO', 'MODIFICACION') NOT NULL,
    `ordenAtendida` VARCHAR(191) NULL,
    `usuario` VARCHAR(191) NULL,
    `domicilio` VARCHAR(191) NULL,
    `observaciones` VARCHAR(191) NULL,
    `seConsumidor` VARCHAR(191) NULL,
    `voltajePrimario` VARCHAR(191) NULL,
    `voltajeSecundario` VARCHAR(191) NULL,
    `subestacion` VARCHAR(191) NULL,
    `agencia` VARCHAR(191) NULL,
    `tarifa` VARCHAR(191) NULL,
    `demCont` VARCHAR(191) NULL,
    `kws` VARCHAR(191) NULL,
    `medicionEn` ENUM('BAJA_TENSION', 'ALTA_TENSION') NULL,
    `cobrar2Porc` ENUM('SI', 'NO') NULL,
    `noCfe` VARCHAR(191) NULL,
    `noFabrica` VARCHAR(191) NULL,
    `marcaMedidor` VARCHAR(191) NULL,
    `tipoMedidor` VARCHAR(191) NULL,
    `codigoMedidor` VARCHAR(191) NULL,
    `codigoLote` VARCHAR(191) NULL,
    `faseElementos` VARCHAR(191) NULL,
    `hilosConexion` VARCHAR(191) NULL,
    `ampsClase` VARCHAR(191) NULL,
    `volts` VARCHAR(191) NULL,
    `rrRs` VARCHAR(191) NULL,
    `khKr` VARCHAR(191) NULL,
    `lectura` VARCHAR(191) NULL,
    `noCaratulas` VARCHAR(191) NULL,
    `multiplicador` VARCHAR(191) NULL,
    `kwTipo` VARCHAR(191) NULL,
    `inst_kwh` VARCHAR(191) NULL,
    `inst_kw` VARCHAR(191) NULL,
    `inst_reactiva` ENUM('KVARH', 'KQH') NULL,
    `ret_kwh` VARCHAR(191) NULL,
    `ret_kw` VARCHAR(191) NULL,
    `ret_reactiva` ENUM('KVARH', 'KQH') NULL,
    `demanda` VARCHAR(191) NULL,
    `inst_indicacion` ENUM('INDICATIVA', 'DIRECTA') NULL,
    `ret_indicacion` ENUM('INDICATIVA', 'DIRECTA') NULL,
    `kwPeriodo` VARCHAR(191) NULL,
    `dias` VARCHAR(191) NULL,
    `escala` VARCHAR(191) NULL,
    `selloEncontrado` VARCHAR(191) NULL,
    `selloDejado` VARCHAR(191) NULL,
    `transf_equipoCompactoNo` VARCHAR(191) NULL,
    `transf_noSerie` VARCHAR(191) NULL,
    `transf_corriente` VARCHAR(191) NULL,
    `transf_potencial` VARCHAR(191) NULL,
    `transf_marcaTipo` VARCHAR(191) NULL,
    `transf_relacion` VARCHAR(191) NULL,
    `transf_garganta` VARCHAR(191) NULL,
    `transf_sellosEncontrados` VARCHAR(191) NULL,
    `transf_sellosDejados` VARCHAR(191) NULL,
    `recibidoPor` VARCHAR(191) NULL,
    `firmaRpeCalibradorBase64` VARCHAR(191) NULL,
    `firmaRpeTecnicoBase64` VARCHAR(191) NULL,
    `firmaRpeJefeBase64` VARCHAR(191) NULL,
    `creadoEn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `actualizadoEn` DATETIME(3) NOT NULL,

    UNIQUE INDEX `M9Mex_folio_key`(`folio`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Evidencia` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `m9mexId` INTEGER NOT NULL,
    `tipo` VARCHAR(191) NOT NULL,
    `filename` VARCHAR(191) NOT NULL,
    `mimeType` VARCHAR(191) NOT NULL,
    `url` VARCHAR(191) NOT NULL,
    `creadoEn` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `Evidencia_m9mexId_idx`(`m9mexId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Evidencia` ADD CONSTRAINT `Evidencia_m9mexId_fkey` FOREIGN KEY (`m9mexId`) REFERENCES `M9Mex`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
